# This workflow calls the master E2E workflow with custom variables
name: UI-E2E
run-name: >-
  ${{ github.event_name == 'workflow_dispatch' &&
      format('[{4}] Rancher-`{0}` - `{1}` destroy={2} dev={3}',
             inputs.rancher_version, inputs.grep_test_by_tag,
             inputs.destroy_runner, inputs.turtles_dev_chart, github.run_number) ||
      github.event_name == 'schedule' &&
      (github.event.schedule == '0 3 * * *' && format('[{0}] Nightly e2e job for `@short`', github.run_number) ||
       github.event.schedule == '0 4 * * *' && format('[{0}] Nightly e2e job for `@vsphere`', github.run_number) ||
       github.event.schedule == '0 5 * * 6' && format('[{0}] Weekly e2e job for `@full`', github.run_number) ||
       'Unknown scheduled job') }}

on:
  workflow_dispatch:
    inputs:
      qase_run_id:
        description: Qase run ID where the results will be reported (auto|none|existing_run_id)
        default: none
        type: string
      rancher_version:
        description: Rancher Manager channel/<version|head_version>[/head_version] to use for installation
        default: head/2.11
        type: string
      turtles_chart_version:
        description: Rancher Turtles chart version to test (eg. 0.21.0)
        type: string
      capi_ui_version:
        description: Version of the capi-ui-extension to test (eg. 0.8.1)
        type: string
      grep_test_by_tag:
        description: Test tags. For multiple selection separate with spaces (Available options - @install [@short @full|@vsphere]). Keep always @install
        required: true
        type: string
        default: '@install @short'
      turtles_dev_chart:
        description: Install rancher turtles dev chart
        default: true
        type: boolean
      destroy_runner:
        description: Destroy the auto-generated self-hosted runner
        default: true
        type: boolean
      skip_cluster_delete:
        description: Skip CAPI cluster and fleet repo deletion tests
        default: false
        type: boolean
      cluster_name_suffix:
        description: Suffix to be used in cluster name (default - github.run_number)
        type: string
      runner_template:
        description: Runner template to use
        default: capi-e2e-ci-runner-spot-n2-highmem-16-template-v3
        type: choice
        options:
          - capi-e2e-ci-runner-spot-n2-highmem-16-template-v3
          - capi-e2e-ci-runner-standard-n2-highmem-4-template-v4
  schedule:
    - cron: '0 3 * * *' # @short
    - cron: '0 4 * * *' # @vsphere
    - cron: '0 5 * * 6' # @full on Saturdays only

jobs:
  ui:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
      gcp_project: ${{ secrets.GCP_PROJECT }}
      pat_token: ${{ secrets.SELF_HOSTED_RUNNER_PAT_TOKEN }}
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      qase_api_token: ${{ secrets.QASE_API_TOKEN }}
      rancher_password: ${{ secrets.RANCHER_PASSWORD }}
      vsphere_secrets_json_base64: ${{ secrets.VSPHERE_SECRETS_JSON_BASE64 }}
      vsphere_endpoints_list: ${{ secrets.VSPHERE_ENDPOINTS_LIST }}
      docker_auth_username: ${{ secrets.DOCKER_AUTH_USERNAME }}
      docker_auth_password: ${{ secrets.DOCKER_AUTH_PASSWORD }}
      docker_registry_config: ${{ secrets.DOCKER_REGISTRY_CONFIG }}
    with:
      test_description: "CI/Manual - UI - Deployment test with Standard K3s"
      cluster_name: cluster-k3s
      destroy_runner: ${{ github.event_name == 'schedule' && true || inputs.destroy_runner }}
      capi_ui_version: ${{ inputs.capi_ui_version }}
      rancher_version: ${{ inputs.rancher_version || 'head/2.11' }}
      qase_run_id: ${{ inputs.qase_run_id || 'auto' }}
      grep_test_by_tag: ${{ inputs.grep_test_by_tag || (github.event.schedule == '0 3 * * *' && '@install @short') || (github.event.schedule == '0 4 * * *' && '@install @vsphere') || (github.event.schedule == '0 5 * * 6' && '@install @full') }}
      turtles_dev_chart: ${{ inputs.turtles_dev_chart == true || (github.event_name == 'schedule' && true) }}
      turtles_chart_version: ${{ inputs.turtles_chart_version }}
      skip_cluster_delete: ${{ inputs.skip_cluster_delete || (github.event_name == 'schedule' && false) }}
      runner_template: ${{ inputs.runner_template || 'capi-e2e-ci-runner-spot-n2-highmem-16-template-v3' }}
      cluster_name_suffix: ${{ inputs.cluster_name_suffix || github.run_number }}
